### ISSUE TITLE
Error occurred when executing KSamplerSeq:  module 'comfy.sample' has no attribute 'broadcast_cond'

### ISSUE THREAD

**Issue by JeffreyBull76** [WASasquatch/WAS_Extras#2]
Running into this error when attempting to use the Ksampler Sequence workflow

-------------------------------------------------------------------------------------------------
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\SD Installs\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD Installs\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD Installs\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD Installs\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\ksampler_sequence.py", line 275, in sample
    unsampled_latent = unsample(model=model, seed=seq_seed, cfg=cfg, sampler_name=sampler_name, steps=steps, end_at_step=end_at_step, scheduler=scheduler, normalize=False, positive=positive_conditioning, negative=negative_conditioning, latent_image=latent_input)[0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD Installs\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\ksampler_sequence.py", line 89, in unsample
    positive_copy = comfy.sample.broadcast_cond(positive, noise.shape[0], device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.sample' has no attribute 'broadcast_cond'
-------------------------------------------------------------------------------------------------

Any ideas what could be causing this?

I am able to generate images using normal Ksampler but not this custom one?

**Comment by WASasquatch** [comment]
Oh yeah, I have a patch for that. Forgot to push it though.

**Comment by JeffreyBull76** [comment]
Ah cool at least I know its not an issue my end. 

No rush as I know its not easy to do but do you have a rough eta on a patch release?

**Comment by WASasquatch** [comment]
https://github.com/WASasquatch/WAS_Extras/commit/2ca7b2a428ec076f2884f104cf0df93f954238e3
